AddressBook/config/routes.rb
AddressBook::Application.routes.draw do
  resources :entries

	root 'entries#index'

  

end

AddressBook/app/models/entry.rb
class Entry < ActiveRecord::Base

require 'formating'

validates_presence_of :first_name
validates_presence_of :last_name
validates_presence_of :email
validates_presence_of :zip_code
validates_presence_of :favorite_color

validates_numericality_of :zip_code
validates :email, format: { with: /[A-Za-z0-9._]+@[A-Za-z0-9._]+\.[A-Za-z]+/}
validate :check_colors
validate :check_zip_codes

	def check_colors
		if !(Formating.valid_color(self.favorite_color))
			errors.add :favorite_color, "is not a valid color. The list of valid colors is at http://www.w3schools.com/html/html_colornames.asp"
		else
			f = File.open("lib/colors","r")
			colors = Array.new
			f.each do |line|
				colors.push(line)
			end
			colors.select! { |string| string.strip!}
			colors.each { |string| 
					if string.downcase == self.favorite_color.downcase
						self.favorite_color = string
					end}
		end
			
	end

	def check_zip_codes
		if !(Formating.valid_zip_code(self.zip_code))
			errors.add :zip_code, "is not a valid zip code."
		end	
	end
end

AddressBook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

AddressBook/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)
    @entry.first_name = params[:entry][:first_name].titleize
    @entry.last_name = params[:entry][:last_name].titleize
    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: 'Entry was successfully created.' }
        format.json { render action: 'show', status: :created, location: @entry }
      else
        format.html { render action: 'new' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end
  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:first_name, :last_name, :email, :zip_code, :favorite_color)
    end
end

AddressBook/app/helpers/address_book_helper.rb
module AddressBookHelper
end

AddressBook/app/helpers/application_helper.rb
module ApplicationHelper
end

AddressBook/app/helpers/entries_helper.rb
module EntriesHelper
end

AddressBook/app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :zip_code %><br>
    <%= f.number_field :zip_code %>
  </div>
  <div class="field">
    <%= f.label :favorite_color %><br>
    <%= f.text_field :favorite_color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

AddressBook/app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

AddressBook/app/views/entries/index.html.erb
<h1>Address Book</h1>
<body>
<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Zip code</th>
      <th>Favorite color</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.first_name %></td>
        <td class="alt"><%= entry.last_name %></td>
        <td><%= entry.email %></td>
        <td class="alt"><%= entry.zip_code %></td>
        <td><%= entry.favorite_color %></td>
	<td bgcolor="<%= entry.favorite_color %>"></td>
        <td><%= link_to 'Show', entry %></td>
        <td class="alt"><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</body>
<%= link_to 'New Entry', new_entry_path %>

AddressBook/app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

AddressBook/app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @entry.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @entry.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @entry.email %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @entry.zip_code %>
</p>

<p>
  <strong>Favorite color:</strong>
  <%= @entry.favorite_color %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

AddressBook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AddressBook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>